var love = [
'BLANK',
'–Inglês',
'I love you',
'–Português',
'Eu te amo',
'– Afrikaans',
'Ek het jou lie',
'– Albanês',
'Unë të dua',
'– Alemão',
'ich liebe dich',
'– Amárico',
'እወድሃለሁ',
'– Árabe',
'أحبك',
'– Armênio',
'Ես սիրում եմ քեզ',
'– Azerbaijano',
'Mən səni sevirəm',
'– Basco',
'maite zaitut',
'– Bengali',
'আমি তোমায় ভালোবাসি',
'– Bielo-russo',
'я цябе кахаю',
'– Birmanês',
'မင်းကိုချစ်တယ်',
'– Bósnio',
'volim te',
'– Búlgaro',
'обичам те',
'– Canarês',
'ನಾನು ನಿನ್ನನ್ನು ಪ್ರೀತಿಸುತ್ತೇನೆ',
'– Catalão',
"T'estimo",
'– Cazaque',
'Мен сені жақсы көремін',
'– Cebuano',
'gihigugma TIKA',
'– Chicheua',
'ndimakukondani',
'– Chinês',
'我爱你',
'– Chona',
'Ndinokuda',
'– Cingalês',
'මම ඔයාට ආදරෙයි',
'– Coreano',
'사랑해',
'– Corso',
'Ti tengu caru',
'– Hatiano',
'Mwen renmen ou',
'– Croata',
'Volim te',
'– Curdo',
'Ez hej te dikim',
'– Dinamarquês',
'jeg elsker dig',
'– Eslovaco',
'Ľúbim ťa',
'– Esloveno',
'Ljubim te',
'– Espanhol',
'te amo',
'– Esperanto',
'mi amas vin',
'– Estoniano',
'Ma armastan sind',
'– Filipino',
'Mahal kita',
'– Finlandês',
'Minä rakastan sinua',
'– Francês',
"je t'aime",
'– Frísio',
'ik hâld fan dy',
'– Gaélico escocês',
'tha gaol agam ort',
'– Galego',
'Quérote',
'– Galês',
"Rwy'n dy garu di",
'– Georgiano',
'მიყვარხარ',
'– Grego',
'Σε αγαπώ',
'– Guzerate',
'હું તને પ્રેમ કરું છુ',
'– Hauçá',
'Ina son ka',
'– Havaiano',
'Aloha wau iā ʻoe',
'– Hebraico',
'אני אוהב אותך',
'– Hindi',
'मैं तुमसे प्यार करता हूँ',
'– Hmong',
'Kuv hlub koj',
'– Holandês',
'ik hou van je',
'– Húngaro',
'Szeretlek',
'– Igbo',
"a hụrụ m gị n'anya",
'– Lídiche',
'איך האב דיר ליב',
'– Indonésio',
'Aku cinta kamu',
'– Ioruba',
'Mo ni ife ti o',
'– Irlandês',
'Is breá liom tú',
'– Islandês',
'Ég elska þig',
'– Italiano',
'Ti amo',
'– Japonês',
'私はあなたを愛して',
'– Javanês',
'Aku tresna sampeyan',
'– Khmer',
'ខ្ញុំស្រឡាញ់អ្នក',
'– Laosiano',
'ຂ້າພະເຈົ້າຮັກທ່ານ',
'– Latim',
'Te amo',
'– Letão',
'Es tevi mīlu',
'– Lituano',
'Aš tave myliu',
'– Luxemburguês',
'Ech hunn dech gär',
'– Macedônio',
'Те сакам',
'– Malaiala',
'ഞാൻ നിന്നെ സ്നേഹിക്കുന്നു',
'– Malaio',
'saya sayang awak',
'– Malgaxe',
'Tiako ianao',
'– Maltês',
'I love you',
'– Maori',
'aroha ahau ki a koutou',
'– Marata',
'मी तुझ्यावर प्रेम करतो',
'– Mongol',
'Би чамд хайртай',
'– Nepalês',
'म तिमीलाई माया गर्छु',
'– Norueguês',
'Jeg elsker deg',
'– Pachto',
'زه ستا سره مینه لرم',
'– Persa',
'دوستت دارم',
'– Polonês',
'kocham Cię',
'– Punjabi',
'ਮੈਂ ਤੁਹਾਨੂੰ ਪਿਆਰ ਕਰਦਾ ਹਾਂ',
'– Quirguiz',
'Мен сени сүйөм',
'– Romeno',
'te iubesc',
'– Russo',
'я люблю тебя',
'– Samoano',
'oute alofa ia oe',
'– Sérvio',
'Волим те',
'– Sessoto',
'kea u rata',
'– Sindi',
'مان توهان سان پيار ٿو ڪيان',
'– Somali',
'waan ku jeclahay',
'– Suaíle',
'nakupenda',
'– Sueco',
'jag älskar dig',
'– Sundanês',
'abdi bogoh ka anjeun',
'– Tadjique',
'Ман туро дӯст медорам',
'– Tailândes',
'ผมรักคุณ',
'– Tãmil',
'நான் உன்னை காதலிக்கிறேன்',
'– Tcheco',
'Miluji tě',
'– Telugo',
'నేను నిన్ను ప్రేమిస్తున్నాను',
'– Turco',
'seni seviyorum',
'– Ucraniano',
'я тебе люблю',
'– Urdu',
'میں تم سے پیار کرتا ہوں',
'– Uzbeque',
'Men seni Sevaman',
'– Vietnamita',
'Anh yêu em',
'– Xhosa',
'ndiyakuthanda',
'– Zulu',
'Ngiyakuthanda',
'– Tupi',
'Oroaûsub'
]
